apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-storage
spec:
  storageClassName: "linode-block-storage-retain"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/abdelrahman/Desktop/k8s-task/shared-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  storageClassName: "linode-block-storage-retain"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi